### ISSUE TITLE
satoshis_per_byte type in MinerFeesItem

### ISSUE THREAD

**Issue by DorskFR** [bitpay/python-bitpay-client#109]
This PR changes the type to `int` https://github.com/bitpay/python-bitpay-client/commit/e9f5bb9dbebeb908b65d67ecf63d0dfe6e5171ce#diff-1f6c66d3002219297e0933038e2e32e06fa67a65b5648dcbec769fa8f57be7da

https://github.com/bitpay/python-bitpay-client/blob/d2b084a43b9a852c57c6ce6ea36de6ddf6aba6e0/src/bitpay/clients/invoice_client.py#L174

When calling `get_invoices` pydantic throws a `ValidationError` with an invoice like this :

```
invoice_data['minerFees']['BTC']
{'satoshisPerByte': 48.667, 'totalFee': 7154, 'fiatAmount': None}
```

works until `5.0.5`

**Comment by bobbrodie** [comment]
Thanks @DorskFR we'll take a look at this. We're working together with a few folks to verify the types and this is one of the fields. We'll get an update in for 6.0.2.

**Comment by bobbrodie** [comment]
@DorskFR I have a PR in that we'll work on reviewing and merging tomorrow. Thanks again!

**Comment by bobbrodie** [comment]
We're preparing the 6.0.2 release, should be out soon :)
