### ISSUE TITLE
Pydantic validation fails for Invoice when there is a refundAddress.

### ISSUE THREAD

**Issue by LysanderGG** [bitpay/python-bitpay-client#89]
Hello, we are encountering a breaking issue with bitpay 5.0.3

```
{"name": "...", "message": "(\"BITPAY-GENERIC: Unexpected Bitpay exception.:BITPAY-INVOICE-GENERIC: An unexpected error occurred while trying to manage the invoice:BITPAY-INVOICE-GET: Failed to retrieve invoice:failed to deserialize BitPay server response (Invoice) : 1 validation error for Invoice\\nrefundAddresses.0\\n  Input should be a valid string [type=string_type, input_value={'r96gztqJozf9f2qeLcKWYS5...:07.032Z', 'tag': None}}, input_type=dict]\\n    For further information visit https://errors.pydantic.dev/2.3/v/string_type\", 103)", "exc_info": "Traceback (most recent call last):\n  File \"/home/abc/Dev/xxx/venv/lib/python3.11/site-packages/bitpay/clients/invoice_client.py\", line 221, in get_invoices\n    invoices.append(Invoice(**invoice_data))\n                    ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/abc/Dev/xxx/venv/lib/python3.11/site-packages/pydantic/main.py\", line 165, in __init__\n    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)\npydantic_core._pydantic_core.ValidationError: 1 validation error for Invoice\nrefundAddresses.0\n  Input should be a valid string [type=string_type, input_value={'r96gztqJozf9f2qeLcKWYS5...:07.032Z', 'tag': None}}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.3/v/string_type\n..., "timestamp": "2024-02-28T10:15:42.197+09:00", "level": "ERROR"}
```

I could confirm that such a refund is pending on Bitpay for this invoice:
```
Refund pending for a 0.000000 BTC (0.123 XRP) overpayment
2/27/24 5:58 PM
Refunding to
r96gztqJozf9f2qeLcKWYS5[...]
Status
Pending
```

**Comment by bobbrodie** [comment]
Hi @LysanderGG do you mean that this was previously working for you in 5.0.2 and is now not working in 5.0.3? We will check this out, but if you could share replication steps that would be helpful. Thanks!

**Comment by LysanderGG** [comment]
Hi, thank you for the quick reply. 
Sorry for the poor wording, it was also not working with 5.0.1 (I could not confirm it was working with a previous version including pydantic). It seems that the API is returning a dict for a field expecting a (list of) string: `refundAddresses`.

I'm not really sure about the replications steps.

What we are doing is calling `get_invoices` (https://developer.bitpay.com/reference/c-full-sdk-retrieve-invoice-filtered-by-query) on a period that includes an invoice with a refundAddress. 
The error we have is with an XRP refundAddress, maybe it is a dict including the address and the memo? I don't know if it's an XRP specific problem or not.

**Comment by bobbrodie** [comment]
Thank YOU! That's helpful. The SDK was fairly minimal before version 4, and that's where we added more API coverage. In version 5 we implemented Pydantic. I'm doing some quick research, and we'll dig deeper into it tonight. Thanks again for the report :)

**Comment by bobbrodie** [comment]
Hey @LysanderGG, just a quick update -- we've made an update and 5.0.4 which should address this issue. We'll plan on creating the release and to push to Pypi tomorrow.

**Comment by bobbrodie** [comment]
@LysanderGG this should be all good now but let us know if you have any issues with 5.0.4. Thanks again!

**Comment by LysanderGG** [comment]
I could test with 5.0.4 and can confirm I don't have the pydantic exception anymore, thank you for the quick fix!

**Comment by bobbrodie** [comment]
Oh sweet, that is great to hear! Thank you so much for reporting it, and I apologize for the little delay there, we needed to update a setting on our account before deploying :)
